server:
  port: 9999
  servlet:
    context-path: /inventory

spring:
    application:
        name: ingredient
    jackson:
        default-property-inclusion: non-null

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ingredientDb?createDatabaseIfNotExist=true
        username: root
        password: Mrgoh@2000

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update

