version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork


  eureka:
    
    build: .
    restart: on-failure
   
    ports:
      - 8761:8761
    networks:
      - mynetwork
 	
   gateway:
    
    build: .
    restart: on-failure
   
    ports:
      - 8085:8085
    networks:
      - mynetwork


  user:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/user?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 1002:1002
    networks:
      - mynetwork


   admin:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/admin?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 1000:1000
    networks:
      - mynetwork


   

 

networks:
  mynetwork: