version: "3.8"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - mynetwork
  eureka:
    build: ./eureka-server
    restart: on-failure
    ports:
      - 8761:8761
    networks:
      - mynetwork	
  gateway:
    build: ./api-gateway
    restart: on-failure
    environment:
       SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka"
       }'
    ports:
      - 8085:8085
    networks:
      - mynetwork
  user:
    depends_on:
      - mysqldb
    build: ./user
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/admin?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'
   
      
    ports:
      - 1002:1002
    networks:
      - mynetwork
  admin:
    depends_on:
      - mysqldb
    build: ./Admin
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "eureka.client.service-url.defaultZone" : "http://eureka:8761/eureka",
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/admin?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"
      }'
    ports:
      - 1000:1000
    networks:
      - mynetwork
networks:
  mynetwork: